name: "Terraform Destroy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_DATABASE_USERNAME: ${{ secrets.TF_VAR_DATABASE_USERNAME }}
  TF_VAR_DATABASE_PASSWORD: ${{ secrets.TF_VAR_DATABASE_PASSWORD }}
  TF_VAR_ACM_CERTIFICATE_ARN: ${{ secrets.TF_VAR_ACM_CERTIFICATE_ARN }}
  TF_VAR_JWT_SECRET_KEY: ${{ secrets.TF_VAR_JWT_SECRET_KEY }}
  TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
jobs:
  undeploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
          AWS_DYNAMODB_TABLE: ${{ secrets.AWS_DYNAMODB_TABLE }}
        run: |
          terraform init \
            -backend-config="bucket=${AWS_BUCKET_NAME}" \
            -backend-config="key=${AWS_BUCKET_KEY_NAME}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${AWS_DYNAMODB_TABLE}"

      - name: Terraform Destroy
        run: |
          TF_LOG=DEBUG terraform destroy \
            -auto-approve \
            -var "DATABASE_USERNAME=${TF_VAR_DATABASE_USERNAME}" \
            -var "DATABASE_PASSWORD=${TF_VAR_DATABASE_PASSWORD}" \
            -var "ACM_CERTIFICATE_ARN=${TF_VAR_ACM_CERTIFICATE_ARN}" \
            -var "JWT_SECRET_KEY=${TF_VAR_JWT_SECRET_KEY}" \
            -var "OPENAI_API_KEY=${TF_VAR_OPENAI_API_KEY}"